---
- name: Update all apt package index cache (apt update)
  apt: update_cache=yes
- name: Install ufw
  apt:
    name: ufw
    state: latest
- name: Allow ssh
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
- name: Allow http(s)
  community.general.ufw:
    rule: allow
    port: 80,443
    proto: tcp
- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Prepare letsencrypt
  include_tasks: letsencrypt.yml

- name: Ensure www has the correct rights
  file:
    path: /var/www/
    state: directory
    mode: "0775"
    group: nginx
    recurse: yes

- name: Configure php
  include_tasks: php.yml

- name: Configure moodle if needed
  include_tasks: moodle_config.yml
  when: moodle_use

- name: Configure nextcloud if needed
  include_tasks: nextcloud_config.yml
  when: nextcloud_use

- name: Run mariadb role
  include_role:
    name: geerlingguy.mysql

- name: run nginx_config role
  include_role:
    name: nginxinc.nginx_config
  vars:
    nginx_config_cleanup: true
    nginx_config_cleanup_files:
      - /etc/nginx/conf.d/default.conf
    nginx_config_debug_output: true
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: numethic.conf
        conf_file_location: /etc/nginx/conf.d/
        servers: "{{ nginx_servers }}"
- name: Ensure correct ownership to /var/www/html
  file:
    path: /var/www/html/
    state: directory
    group: nginx
    owner: nginx
- name: Set home directory for nginx user to /var/www/html
  ansible.builtin.shell: systemctl stop nginx && systemctl stop php{{ php_version }}-fpm && usermod -d /var/www/html/ nginx && systemctl start nginx && systemctl start php{{ php_version }}-fpm

- name: Challenge letsencrypt certificate
  include_tasks: letsencrypt_challenge.yml

- name: Install moodle if needed
  include_tasks: moodle_install.yml
  when: moodle_use

- name: Install nextcloud if needed
  include_tasks: nextcloud_install.yml
  when: nextcloud_use
