- name: Install moodle
  ansible.builtin.shell: "sudo -u nginx php admin/cli/install.php \
  --lang=fr \
  --wwwroot=https://{{ moodle_domain }} \
  --dataroot=/var/www/html/moodledata \
  --dbtype=mariadb \
  --dbname={{ moodle_db_name }} \
  --dbuser={{ moodle_db_user }} \
  --dbpass={{ moodle_db_pwd }} \
  --fullname='{{ moodle_fullname }}' \
  --shortname='{{ moodle_shortname }}' \
  --adminuser={{ moodle_admin_username }} \
  --adminpass={{ moodle_admin_pwd }} \
  --adminemail={{ moodle_admin_email }} \
  --non-interactive \
  --agree-license
  "
  args:
    chdir: /var/www/html/moodle/
    creates: /var/www/html/moodle/config.php

- name: Install moosh
  ansible.builtin.shell: curl -o /tmp/moosh.zip https://moodle.org/plugins/download.php/25295/moosh_moodle311_2021101200.zip && unzip /tmp/moosh.zip -d /var/www/html/ && rm /tmp/moosh.zip
  args:
    creates: /var/www/html/moosh/

- name: Install plugin Multi-Embed filter
  ansible.builtin.shell: sudo -u nginx sh -c '/var/www/html/moosh/moosh.php plugin-install -f filter_multiembed && php admin/cli/upgrade.php --non-interactive'
  args:
    chdir: /var/www/html/moodle/
    creates: /var/www/html/moodle/filter/multiembed/filter.php

- name: Install plugin Tiles format
  ansible.builtin.shell: sudo -u nginx sh -c '/var/www/html/moosh/moosh.php plugin-install format_tiles && php admin/cli/upgrade.php --non-interactive'
  args:
    chdir: /var/www/html/moodle/
    creates: /var/www/html/moodle/course/format/tiles/format.php

- name: Install plugin Lightbox Gallery
  ansible.builtin.shell: sudo -u nginx sh -c '/var/www/html/moosh/moosh.php plugin-install mod_lightboxgallery && php admin/cli/upgrade.php --non-interactive'
  args:
    chdir: /var/www/html/moodle/
    creates: /var/www/html/moodle/mod/lightboxgallery/index.php
