---
- name: Install a list of needed packages
  apt:
    pkg:
    - unzip
    - git
    - php-gd
    - php-mysql
    - php-curl
    - php-mbstring
    - php-intl
    - php-gmp
    - php-bcmath
    - php-imagick
    - php-xml
    - php-zip

- name: Build database and user dict
  set_fact:
    nextcloud_db:
      - name: "{{ nextcloud_db_name }}"
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    nextcloud_user:
      - name: "{{ nextcloud_db_user }}"
        password: "{{ nextcloud_db_pwd }}"
        priv: "{{ nextcloud_db_name }}.*:ALL"

- name: Append nextcloud database
  set_fact:
    mysql_databases: "{{ mysql_databases + [ nextcloud_db ] }}"
    mysql_users: "{{ mysql_users + [ nextcloud_user ] }}" 

    
- name: Build nginx config dict
  set_fact:
    nextcloud_server_http:
      listen:
        listen_localhost:
          port: 80
      server_name: "{{ nextcloud_domain }}"
      root: /var/www/html/letsencrypt/
      web_server:
        locations:
          letsencrypt:
            location: /.well-known/acme-challenge
            try_files: $uri $uri/ =404
          main_site:
            location: /
            custom_options:
              - "rewrite ^ https://{{ nextcloud_domain }}$request_uri? permanent;"
    nextcloud_server_https:
      listen:
        listen_ssl:
          port: 443
          ssl: true
      ssl:
        cert: "/etc/letsencrypt/live/{{ nextcloud_domain }}/fullchain.pem"
        key: "/etc/letsencrypt/live/{{ nextcloud_domain }}/privkey.pem"
      server_name: "{{ nextcloud_domain }}"
      root: /var/www/html/nextcloud
      custom_options:
        - index index.php;
      web_server:
        locations:
          main_site:
            location: ~ [^/]\.php(/|$)
            custom_options:
              - fastcgi_split_path_info ^(.+\.php)(/.+)$;
              - fastcgi_index index.php;
              - "fastcgi_pass unix:/run/php/php-fpm.sock;"
              - include fastcgi_params;
              - fastcgi_param PATH_INFO $fastcgi_path_info;
              - fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

- name: Append nginx nextcloud conf
  set_fact:
    nginx_servers: "{{ nginx_servers | combine({'nextcloud_http': nextcloud_server_http, 'nextcloud_https': nextcloud_server_https}) }}"

- name: Check nextcloud folder exists
  stat:
    path: /var/www/html/nextcloud
  register: nextcloud_dir

- name: Download nextcloud 23
  ansible.builtin.shell: sudo wget -c https://download.nextcloud.com/server/releases/nextcloud-23.0.0.tar.bz2 -O - | sudo tar -xj -C /var/www/html/
  args:
    chdir: /var/www/html
  when: not nextcloud_dir.stat.exists

- name: Ensure nextcloud folder exists and has the correct permissions
  file:
    path: /var/www/html/nextcloud
    state: directory
    group: nginx
    owner: nginx
    recurse: yes

- name: "Copy selfsigned cert to have a working nginx server to ask a legitimate cert"
  shell: "mkdir -p /etc/letsencrypt/live/{{ nextcloud_domain }}; cp /etc/ssl/private/selfsigned.key /etc/letsencrypt/live/{{ nextcloud_domain }}/privkey.pem; cp /etc/ssl/certs/selfsigned.crt /etc/letsencrypt/live/{{ nextcloud_domain }}/fullchain.pem; touch /etc/letsencrypt/live/{{ nextcloud_domain }}/selfsigned;"
  args:
    creates: "/etc/letsencrypt/live/{{ nextcloud_domain }}/privkey.pem"
